
#logging.level.root=debug
#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate=error


cryptobot.trade.evaluation.scheduler.cron = 10 */5 * * * *
cryptobot.cotation.evaluation.scheduler.cron = 20 0 * * * *
cryptobot.position.scheduler.cron = 20 */5 * * * *
cryptobot.reset.evaluation.scheduler.cron = 0 2 0 * * SUN


cryptobot.mexc.restclient.proxy.adr 
cryptobot.mexc.restclient.proxy.port 

cryptobot.logging.directory = ./log